### ISSUE TITLE
Atomic operations EAV

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bcc#143]
Win10 x64 builds - the AtomicSwap, CompareAndSwap and AtomicAdd functions give an EAV each.

    Strict
    Local atomic:int
    AtomicAdd(atomic,1)
    AtomicSwap(atomic,1)
    CompareAndSwap(atomic,1,1)

**Comment by GWRon** [comment]
BlitzMax NG relies on "bdwgc" - the Boehm Garbage Collector. Maybe the version Brucey uses, has problems with the 64bit build?

`CompareAndSwap` (and others) are defined in `brl.mod/threads.mod/threads.bmx` and they directly use `bbAtomicCAS()` (defined in `blitz_thread.c` in the very same directory). This function then uses `__sync_val_compare_and_swap` on non-android devices.

If there is no failure within that chain, the erroneous part will be somewhere in the bdwgc-code.

Else:
Maybe `AtomicAdd` is destroying/invalidating the content of `atomic` - so that it is no longer an "atomic".

**Comment by woollybah** [comment]
It's a problem within threads.bmx, or possibly the way ```Int Var``` is interpreted for an argument in an external function.
Declaring the extern params as Int Ptr and casting via VarPtr will solve the issue.

**Comment by woollybah** [comment]
Fixed in brl.mod
