### ISSUE TITLE
Unable to convert from Object Array to Byte Ptr

### ISSUE THREAD

**Issue by Leushenko** [bmx-ng/bcc#152]
NG doesn't like my code that implicitly passes an `Object[]` to a `Byte Ptr` argument.

Example:

    Function ArraySort(a:Object[], cmp:Int(l:Object Var, r:Object Var)) NoDebug
    	Extern "C"
    		Function qsort(base:Byte Ptr, num:Int, sz:Int, cmpf:Byte Ptr)
    	End Extern
    	qsort(a, a.Length, SizeOf(Byte Ptr(0)), cmp)  '<-- error on a
    End Function

This is easily silenced in-code by changing `a` to `Object(a)`, which implicitly-converts fine.

(it then runs into a problem with the `Extern` function, but that's another story)

**Comment by woollybah** [comment]
Casting to Object may convert fine for compilation, but it would probably result in a crash at runtime - since array data and Object data start at different offsets.
This could be "fixed", but your objects would end up much larger in order to align the data.
Another option would be to add a pointer to a table of info. This could be null for normal types, and an actual info structure for arrays. Object fields and array data could then be aligned to the same offset in the "object".

**Comment by Leushenko** [comment]
Ah yeah good point. I never got that far anyway thanks to the other problem.

My guess is that that "fix" is not what the average user likely wants... if the object is typed as `Object` going into the conversion, Principle Of Least Surprise says it's because you actually want the complete object data, right?

If you did want to implement it that way though, unless I misunderstand, wouldn't it be easier  - instead of adding extra data - to simply do a runtime test whether the object is an array, and convert accordingly? (`If Array(o) bbArrayToBytePtr Else bbObjToBytePtr`) This would trade reduced performance of the conversion operation for zero increase in space usage.
