### ISSUE TITLE
Cannot use widened return type in function pointers (Regression)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#258]
With @HurryStarfish's Pullrequest #243 (leading to merge 164ce92fc150907694150e86bcba3c1eedf23650) it is no longer possible to override the return type of a function passed as function pointer to another function.
 
```BlitzMax
SuperStrict
Framework Brl.StandardIO


Type TBaseClass
End Type

Type TMyClass Extends TBaseClass
End Type


Function RegisterFunction(func:TBaseClass())
	'do something
End Function

Function CreateMyClass:TMyClass()
	Return New TMyClass
End Function


RegisterFunction( CreateMyClass )
```

Output:
```
Compile Error: Unable to find overload for registerfunction(TMyClass()). Argument #1 is "TMyClass()" but declaration is "TBaseClass()". 
```

**Comment by GWRon** [comment]
BTW: While "SCT" (Simple Code Tester) might have some flaws - we could still use it to have all these "should work"-samples added there so we find regressions faster.

**Comment by HurryStarfish** [comment]
Ah, this is because before my changes, bcc simply considered all function pointer types equal, disregarding parameters and return types. Now it does a proper "extends" check, but that check currently requires the return types to be identical.
I just looked into that and it's a simple fix; but before I create the pull request, here's a question:

Since function pointers are already covariant on the return types - should we also make them contravariant on the parameter types? In other words, should we allow this?
```
SuperStrict
Framework Brl.StandardIO


Type TBaseClass
End Type

Type TMyClass Extends TBaseClass
End Type


Function RegisterFunction(func:TBaseClass(param:TMyClass))
	'do something
End Function

Function CreateMyClass:TMyClass(param:TBaseClass)
	Return New TMyClass
End Function


RegisterFunction( CreateMyClass )
```


This is not allowed in vanilla (the parameter types must be strictly identical there), but I don't see why not? It wouldn't break compatibility and it would give function pointers some more flexibility.

**Comment by GWRon** [comment]
Dunno if you have a little error in your code but `RegisterFunction()` espects a pointer to a function accepting a param of "at least" `TMyClass`. The function you are then registering, only provides `TBaseClass`.

So I assume you mean:
```BlitzMax

Function RegisterFunction(func:TBaseClass(param:TBaseClass))
	'do something
End Function

Function CreateMyClass:TMyClass(param:TMyClass)
	Return New TMyClass
End Function


RegisterFunction( CreateMyClass )
```
Which is still not possible in vanilla - and maybe a nice addition to "NG". Problem is that it breaks with compatibility to NG without being "obvious". A new command or "syntax" is what vanilla blitzers recognize, but especially with framework code I think it might become a bit hard to recognize (not knowing about `TBaseClass` and `TMyClass`).

**Comment by HurryStarfish** [comment]
No, the version I provided is the correct one. Consider this (using the code from my post above):

RegisterFunction expects func to return something that is compatible with a TBaseClass - if CreateMyClass actually returns something more derived, no problem!
But with parameters, it needs to be the opposite: RegisterFunction expects func to be able to accept anything that's a TMyClass - if CreateMyClass actually accepts _more_ (i.e. something less derived), then that's no problem either.

The code you just quoted on the other hand, can not be allowed, because if RegisterFunction tried to call func and pass "New TBaseClass" to it, and then CreateMyClass tried to access a member that is only present in TMyClass, it would crash.

**Comment by GWRon** [comment]
Had to read it three times ...not accepting what you wrote. And then it made "click".

Last paragraph of my previous reply still is something we should consider (recognizing "NG features").

**Comment by HurryStarfish** [comment]
Sorry, I didn't know how to describe it well, maybe I should have given more example code?

As for the other concern:
If I understand you correctly, you seem worried about NG features that are not immediately recognizable as NG-exclusive from the syntax. But I would argue that NG has such features already. The recent improvement of auto-arrays to allow things like `Local x:Float[] = [1, 2, 3.5]` is probably the best example. Other features, such as access modifiers within types or combining "?"-flags with And/Or, might also not be obvious to anyone who doesn't know the language inside-out. But in any case, vanilla catches all those things during compilation, so anyone trying to write vanilla<>NG cross-compatible code immediately sees them once they try to compile the code in vanilla.
Function pointers seem to be a relatively "advanced" feature anyway, so I wouldn't expect inexperienced users to stumble about this and get confused. As long as it doesn't change the behavior of vanilla code (which it doesn't), IMO it should be fine.

**Comment by GWRon** [comment]
Hmm, convinced.
You are entitled to implement this feature :-)

Regarding "? and or" - it is not catched during compilation. Vanilla falls back to "false" if a condition is unknown to bcc. So a `?bmxng` is considered "false". So far so good, but `?win32 or linux` is also considered "false" in all cases. 

Nonetheless you are right that most things are for more advanced users so it might not be that big troublemaker feature. Dunno what @woollybah thinks about it.

**Comment by HurryStarfish** [comment]
Unknown ?-flags are considered false, but if And/Or are involved, my version of vanilla does spit out an [error](http://puu.sh/uaKUF.png).
Alright, I've made a pull request including both the fix and the "bonus" feature, but I made them two separate commits.

**Comment by woollybah** [comment]
I believe this is working now.
