### ISSUE TITLE
Inner types of different template parameters fails to compile

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#319]
As long as the inner type params are at least part of the main type's this should work...
```blitzmax
SuperStrict

Framework brl.standardio

Local gen:TGen<Int, Float> = New TGen<Int, Float>(100, 45.5)

Type TGen<X, Y>

	Field vx:TGenX
	Field vy:TGenY

	Method New(v1:X, v2:Y)
		vx = New TGenX(v1)
		vy = New TGenY(v2)
	End Method

	Type TGenX<X>
		Field value:X
		
		Method New(value:X)
			Self.value = value
		End Method
		
	End Type
	
	Type TGenY<Y>
		Field value:Y
		
		Method New(vlaue:Y)
			Self.value = value
		End Method
	End Type

End Type
```
Instead, it complains that the params for TGenX do not match those for TGen.

**Comment by HurryStarfish** [comment]
Is it necessary for type parameters on inner types to get such special treatment?
IMO it would be more intuitive and useful if the outer type's type parameters were implicitly visible to inner classes, just like they are to other members. This is how it works in Java and in C# as well:

```
Type TGen<X>
	Method M()
		Local value:X ' M is a member of TGen, so X is visible here
	End Method

	Type TGenInner
		Field value:X ' TGenInner is a member of TGen, so X is visible here
	End Type
End Type
```

If any code somewhere inside TGen wants to refer to TGenInner, then X is already known. If code outside TGen wants to refer to it, one would only have to write `TGen<Int>.TGenInner` instead of the redundant `TGen<Int>.TGenInner<Int>`.
If TGenInner declared its *own* <X> however, then the two X would be different from each other. In that case, the "new" X would then hide the "old" one, just like regular variables can hide each other:

```
Type TGen<X>
	Field blah:Int

	Method M(blah:Int) ' hides the outer blah within this method
		Local test:Int = blah ' refers to M's own parameter
	End Method

	Type TGenInner<X> ' hides the outer X within this method
		Field test:X ' refers to TGenInner's own type parameter
	End Type
End Type
```
