### ISSUE TITLE
Accessing element in empty array leads to incorrect behaviour

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#324]
Based on the code of the last issue I recognized that NG currently does something undesired: when accessing an array "out of bounds" it seems to not correctly check conditions then:

```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.GLMax2D


Local Img:TImage[]
If( Img[0] = Null)
  Print "fail"
Else
  Print "success"
EndIf
```
While it fails in Debug (OOB error) it prints `success`in release mode - which means it thinks that `Img[0]` is containing a valid `TImage` object ...

**Comment by GWRon** [comment]
But shouldn't it check if the thing behind 'img[0]" be checked if it is a TImage compatible object?

**Comment by woollybah** [comment]
Okay, so imagine we added the ability to do that, and in my app I have a null img array and I try to access img[400], which just so happens to point to a real TImage object at that particular bit of memory.

Is that valid?

And if, in the first instance, you had ```If Img Then``` you'd never get into this situation at all.

**Comment by GWRon** [comment]
Ahh think I got it.

So it is "not null" as is does not exist at all - if you created the img array with a size of 10, it would be null, as it is a "null object" at this position in the array.

**Comment by HurryStarfish** [comment]
> So it is "not null" as is does not exist at all

Pretty much. It is "not null" because it is not checking an actual object reference, it's checking whatever happened to be lying around at the point in memory you were accessing.

In Debug builds, BlitzMax does bounds checks, so you will get an exception if you try to access an element at a nonexisting index (which, on an empty array, is any index, including `[0]`).
In Release builds, the checks are left out for improved performance. So your example will just access some "random" data outside the array and try to treat it as if it was a TImage, which is likely to lead to bad things happening sooner or later (random behaviour and/or crashes).

The same applies to Null checks: trying to access a field or method of a Null object will not be checked in Release mode; you'll only get an exception in Debug mode (and even then, [NG currently misses the check on methods](286)).
