### ISSUE TITLE
"Debugger Error:Invalid scope kind" when stepping over control flow statement within a Try block

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#328]
I've found this while implementing the Finally blocks, then realized it happens on the master branch as well:
```
SuperStrict
Framework BRL.StandardIO

Print F()
Print F()
Function F:Int()
	DebugStop
	Try
		Return 5
	Catch e:Int[]
	End Try
End Function
```
Running this in debug mode and using the debugger to step over the Return aborts the program with the message `Debugger Error:Invalid scope kind`.
Same goes for this:
```
SuperStrict
Framework BRL.StandardIO

Print F()
Print F()
Function F:Int()
	DebugStop
	For Local i:Int=1 To 1
		Try
			Exit
		Catch e:String
	End Try
	Next
End Function
```
And this leads to an EAV:
```
SuperStrict
Framework BRL.StandardIO

Print F()
Print F()
Function F:Int()
	DebugStop
	For Local i:Int=1 To 1
		Try
			Return 5
		Catch e:String
	End Try
	Next
End Function
```

I am guessing this has to do with a wrong amount of `bbExLeave()` or `bbOnDebugPopExState()` being generated before the Exit or Return in question. I am not currently sure how to fix this, so it would be nice if Brucey or someone else could take a look at that.
A fix should probably wait until after the upcoming pull request for Finally blocks though, since that feature brings some changes to the way Try blocks, and control flow statements within them, are handled.

**Comment by woollybah** [comment]
All this stack stuff is very exciting!

There are basically 2 stacks in operation. One keeps track of the local scope, the other is the exception stack.

The exception stack also has a reference to the local scope at the start of the Try, in order to be able to jump back to that point of local scope when exiting the Try.

There are obviously some issues with coordinating all the relevant parts...

Example 2 has a problem because the Try snapshots the local scope of the loop, but the Exit needs to break back to the function scope. So there's a missing ```bbOnDebugLeaveScope()```. to get the Exit out of the loop scope. This needs to occur **after** the call to ```bbOnDebugPopExState()``` because that function is resetting the current scope, so you should end up with something like :
```c
		bbExLeave();
		bbOnDebugPopExState();
		bbOnDebugLeaveScope();
		goto _exitjmp1;
```

Example 3 should work in a similar way, but is currently very broken, as there are some calls to ```bbOnDebugLeaveScope()``` before the Ex functions. In this case it requires two calls to ```bbOnDebugLeaveScope()``` before returning, as it has to exit the local scope of the loop and the the function scope, so I would expect to see something like :
```c
		bbExLeave();
		bbOnDebugPopExState();
		bbOnDebugLeaveScope();
		bbOnDebugLeaveScope();
		return 5;
```

**Comment by HurryStarfish** [comment]
The really confusing thing here is not just the funky control flow that Finally blocks can cause, but also the fact that there are _four_ different "try stacks" to pay attention to. The first two are the tryStack and loopTryStack in in translator.bmx that keep track of the code structure at compile time. The third one is the one in blitz_ex.c that's actually used for the exception mechanism. And the fourth one is the one that's used by the debugger here.
I've got the first three under control now (I _hope_ there aren't any special cases left that I've missed), but I am not yet sure how the fourth one works exactly and how it's supposed to interact with the blitz_ex stack, since I've had to change the behaviour of the latter.
Since Finally blocks seem to be working correctly at least in release mode now, I think I'll put up a pull request today (assuming I don't break anything trying to merge the current master branch in), so you can at least take a look at the changes.

**Comment by HurryStarfish** [comment]
[Pull request is up.](https://github.com/bmx-ng/bcc/pull/330)

**Comment by woollybah** [comment]
I have a fix for number 2, and I'll use a similar tactic for Returns too.
The idea is to provide more information in TBlockDecl - a block type... loop, try, finally, etc.
It simplifies things when it comes time to walk the scope stack looking for certain types.

**Comment by woollybah** [comment]
Hopefully the latest commit solves all the outstanding problems with these scope stack errors.
