### ISSUE TITLE
Implement a ReadOnly property.

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#343]
As mentioned in #338 and #333, it would be useful to have some way of declaring a property of read-only to a variable - primarily this would be of use for variables declared in the new Using block headers, but as a side-effect could be applied to Fields, fixing the issue with .length field modifications as raised in #338.

As far as I can tell, implementing anything other than a simple re-assignment prevention would require a level of static-analysis that is quite infeasible.
So I'm happy to just provide basic prevention, catching any attempts to modify the base variable. An instance of an object therefore, would be fixed in the field, but its content could be changed. Array content could be manipulated. Primitive values would not be modifiable, other than via some pointer trickery (var, varptr, etc) .

The keyword ReadOnly seems fine, and presents a fairly obvious description of its intention.

**Comment by woollybah** [comment]
I've implemented this, and it's ready to be committed, unless anyone has any further comments?

**Comment by HurryStarfish** [comment]
In the process of implementiong Using statements, I already added a `Const DECL_READONLY:Int=    $40000000` flag in decl.bmx which can be used in the TLocalDecl "attrs" and checks/errors to disallow reassignment. I think I could pretty easily extend this to fields. If you implemented if in a different way though and prefer to use that, you can commit it and I can change the Using variables accordingly.

I think the best compromise for making read-only fields useful without requiring any fancy static analysis would be:
- allow assignments to them in the constructors of the type (= treat them like a regular field)
- but disallow assignments anywhere else

This would mean the field would be "read-only" not immediately after being initialized (as it could still be reassigned in a constructor), but after the object/instance is fully constructed.

`Primitive values would not be modifiable, other than via some pointer trickery (var, varptr, etc) .`
I would draw the line *between* Var and Varptr: I consider Var parameters a "regular" language feature (theyre type- and memory safe), so passing something that is read-only as a Var parameter should count as an assignment and be disallowed (except in constructors). Pointers on the other hand are an "advanced" feature can break pretty much anything, so there's probably not much of a point in disallowing Varptr.

**Comment by HurryStarfish** [comment]
I had also considered allowing class/struct member Globals to be read-only. On the one hand, they could be useful for a few things (singleton objects, lookup table arrays). But on the other hand, they would require direct initialization in the line that declares them, and [this can be problematic](https://github.com/bmx-ng/bcc/issues/252), so maybe we should hold off on that for now.

**Comment by woollybah** [comment]
If you have a look at the change to stmt.bmx, you'll see the readonly check for field assignments. It shouldn't be too hard to adapt it for your use.
In decl I added DECL_READ_ONLY, and IsReadOnly() to TDecl.
Read only fields in .i files are prefixed with @ instead of .
I haven't applied the change to brl classes .i file yet as it requires (again) that bcc and brl are in-sync, which tends to be a problem for people. So I'll probably update brl when I do the next release.

**Comment by woollybah** [comment]
The latest commit adds a test for ReadOnly Var usage.

**Comment by HurryStarfish** [comment]
Alright; I'll get to this as soon as I have the time.

**Comment by HurryStarfish** [comment]
`ReadOnly` is currently the very last element of a field declaration.
I think that's not the best choice, because in the presence of an init expression, the `ReadOnly` attribute gets detached from the declaration it belongs to:
```
Type TTest
	Field i:Int = 1 + 2 * SomeFunction() ReadOnly
End Type
```
This can look quite confusing, especially with long init expressions or ones that are split across multiple lines with `..`.

I'd like to move the attribute directly after the `Field` keyword:
```
Type TTest
	Field ReadOnly i:Int = 1 + 2 * SomeFunction()
End Type
```
This would make the syntax consistent with operators: we can consider `Field ReadOnly` a kind of type member that is technically still a field, but a special one that is treated a bit differently from normal fields; just like a `Method Operator` is technically a method, but called in a different way than normal ones.

Is that fine, or do you have any objection?

**Comment by HurryStarfish** [comment]
You're certainly right about meta tags; I actually forgot about them, since they're fairly rare in practice. I'd say they're not ideal either. Other languages usually put such things in front/above the declaration, like we do with bbdocs. `Abstract` and `Final` are also appended, though they only apply to things which can't be initialized with `=`. But in any case, even if we wanted to, we couldn't change the position of any of those anyway, since it would be breaking backwards compatibility.
`ReadOnly` is a new feature, so we can still choose where to put it. I agree that consistency is important, and I probably wouldn't have suggested `Field ReadOnly` if that sort of syntax was without precedent. But since `Method Operator` exists, we have both the "goes at the end" and the "goes after the main keyword" form in BlitzMax-NG already. So I'd say it comes down to what looks more logical and readable. My opinion is this:
- `Field ReadOnly` is somewhat similar to `Method Operator`, like I mentioned in the previous post
- It's not so similar to `Abstract` and `Final`, those two are specifically about inheritance.
- The way you use such a field is like something inbetween `Field` and `Const`, so it's intuitive to keep the two parts together, almost as if `Field ReadOnly` was a single keyword.

It would be good to hear other people's opinions on this.

**Comment by woollybah** [comment]
I'm fine either way, and it's not difficult to change the order.

**Comment by woollybah** [comment]
Moved it to after the Field keyword.
