### ISSUE TITLE
Localizable Error Messages

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#357]
Would it be useful to have error messages localizable?

Or can we just assume that everyone speaks English? :-)

**Comment by GWRon** [comment]
On the one hand localization helps to spread the word for people not being able to read and write English.
But on the other hand NG does not have the spread yet which it would need to allow eg. searching for a localized Error message and then find a dozen of "QA" for this issue.

So to increase chances of finding solutions for potential errors I would keep it at "English".

Nonetheless: _preparing_ the language to use localization files (.po or so?) might be nothing "worthless" (thinking of stuff like "packages" for linux so people could install/update it easier).

**Comment by HurryStarfish** [comment]
Yeah, probably unnecessary. .NET does thing sort of thing - it also auto-translates exception messages - and it's a major annoyance because it makes them very hard to look them up online. Trying to understand a stack trace or log someone else has sent to you can also be a problem. Programmers speak English anway, so I don't think we need errors/exceptions localized.
