### ISSUE TITLE
Shared Libraries (DLLs) and brl.Thread leads to segfault/EAV

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#366]
When compiling a DLL with sources utilizing Brl.Threads this will lead to an EAV within the calling application.

This also means that you cannot use one of the modules importing Brl.Threads. As Brl.LinkedList (`TList`) uses Brl.Threads this means you also loose Brl.Retro and other modules.

Within Brl.Threads it seems that `Type TThreadData.SetValue()` fails to properly call `bbThreadDataSet`. I tried to wrap it in "try catch" but it did not properly catch it.

**Comment by woollybah** [comment]
I think the way BlitzMax initialises on load is the main issue when built as a DLL. The problem is, all the initialisation is then done via DLLMain, which is called as part of the library load.

We should probably consider adding some kind of "init" function that the user of the DLL needs to call once the DLL is loaded. This would avoid the creation of threads and such from DLLMain - which is considered bad practise, and may even be disallowed...

**Comment by GWRon** [comment]
Hmm, so something which "throws" if not done? A function which is only included in the binary when build as "sharedlib" ...
Maybe even something like this:

```
Function APP_INIT()
?sharedlibrary
  throw "Shared libraries need to cover some initialization aspect. You need to override APP_INIT() and handle it on your own."
?
End Function
```
Then just call `APP_INIT()` regardless of building type ?!

**Comment by woollybah** [comment]
I'll probably add something like `InitBRL()` (for init blitz runtime library) as an extra exported function, and have the default "built-in" DLLMain do nothing.

The library user would then be required to call InitBRL() before calling any other function. Calling a function before initialising would result in undefined behaviour.

**Comment by woollybah** [comment]
Is this still an issue?

**Comment by GWRon** [comment]
Don't thino so.
