### ISSUE TITLE
Max(number, object) possible but not in vanilla

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#367]
```BlitzMax
SuperStrict

Framework Brl.StandardIO
Import Brl.Math
Import Brl.Pixmap

Local obj:Object = New TPixmap
Local i:Int = 10

Print Max(i, obj)
```

In NG the memory address of "obj" is used while vanilla outputs an error: `Compile Error: Operator 'Max' can only be used with numeric types`

Is this a feature or a bug?

**Comment by HurryStarfish** [comment]
Certainly looks like a bug. This is basically an implicit Object to Int conversion which doesn't exist anywhere else in the language; and `Max` (along with other things like `Min` `Abs` and `Sgn`) is one of those odd irregular things in the language that look like functions but act more like operators, so I wouldn't be all that surprised about a bug appearing there.

That said, maybe it's time to decide on what those things actually *are*. Their special role in legacy BlitzMax was justified out of neccessity, but in NG, we could now fix that.
I think they should be treated either as regular

- **Operators**, which means overloading them should be possible (it would make sense for a vector type to overload `Abs` to return its magnitude, for example), or as regular
- **Functions**, which means they should be defined in `brl.mod/blitz.mod/blitz.bmx` like other built-in functions, except with overloads for all the built-in types (`Function Abs:Int(i:Int)`, `Function Abs:Float(i:Float)`, ...) ***

Neither of these were possible in legacy because operator and function overloading didn't exist, but it is now.

\*** Additionally, I imagine that at some point in the future, once generics have matured, it could be possible to allow structs to implement interfaces, like they can in C#. Then we could have a set of basic math interfaces like `IComparable`, `ISummable` etc. which would also be implemented by built-in types like `Int` and `Float`. And at that point these functions could be upgraded to truly generic functions such as `Function Max<T>:T(x:T, y:T) Where T Implements IComparable<T>`

**Comment by GWRon** [comment]
Brucey now implemented your suggestion and replaced Min/Max with normal "functions".

So what does that now mean? If you used `Max(intValue, doubleValue)` you get a warning of parameters being of the wrong type. So for now you needed to add casts everywhere - or implement an overloaded method of each "variant:
Max(int, double)
Max(int, float)
...
Max(float, double)

Or would it be kind of "dirty" to have meta tags (for compilation, not runtime) defining whether casts are silently allowed (int+float -> float+float, double+int -> double+double, ...) ?
Such an addition could benefit some more functions (just think of a DrawImage() only accepting ints - while you store floats for the position as it "moves on the screen").

**Comment by HurryStarfish** [comment]
> If you used Max(intValue, doubleValue) you get a warning of parameters being of the wrong type.

 Really? I can't test this right now, but I thought that these kinds of conversions were performed silently. So as long as there is `Max:Double(a:Double, b:Double)`, a call like `Max(intValue, doubleValue)` should convert the Int to a Double without giving a warning. Or has this been changed recently?

**Comment by GWRon** [comment]
Oh, you are right - I was not able to test it right ahead as I was in trouble with sdl.mod (segfaults) and recompilation issues with new code (brl.blitz required by pub.lua as this uses min/max()).

It only blames if the definition was "Max(i:int, i2:int)" and you gave it a double ... so as said you are right and this is no issue.
