### ISSUE TITLE
Consider new Enum support

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#382]
Up until now in BlitzMax, we would likely use a Const to define an enumerated value, like so:
```blitzmax
Const LEFT:Int = 0
Const RIGHT:Int = 1

Direction(LEFT)

Function Direction(dir:Int)
End Function
```
However, Blitzmax does not enforce the validity of the values, which must instead be implemented by the user.

If Enum were part of the language, BlitzMax could automatically type check variables and arguments as part of the compilation process.

```blitzmax
Enum EDirection
    Left,
    Right
End Enum

Direction(EDirection.Left)

Function Direction(dir:EDirection)
End Function
```

An enumeration would be an incrementing integer ordinal with a 0 base. Providing a value for each enumeration would be optional, but you could override them individually..
```blitzmax
Enum EAction
    Stop,
    Go,
    Run = 10,
    Fly
End Enum
```
In the above example, the values of the enumeration would be 0, 1, 10, 11, respectively.
Enumerations should always be ordered - i.e. you can't have an order of 10, 1, 11.
An enumeration can also be used as the value of another.
```blitzmax
Enum EAction
   Stop,
   Pause = Stop,
   Go
...
```
Where Stop and Pause have the same value.

Negative values are also a possibility if the intial value is set to a negative?

Internally, the enumerations would render as their actual ordinal values, in the same way that Consts do.

Whether we allow ints/enums to be directly interchangeable is a design decision, which both have pros and cons.

**Comment by HurryStarfish** [comment]
For now, I'll just throw out everything that comes to mind. I think the following should be discussed:

- **What "kind" of type will enums be?**
Currently, there are three "kinds" (I don't know any better term for this) of user-defined types in BlitzMax: classes, structs and interfaces. As for the the built-in types, some of them (namely `Object`, `String` and arrays, which are all classes) fit in with this system. But other built-in types (numbers, pointers, function types, intrinsics) do not; rather, they're special cases. At some point in the future, I would like to streamline the type system a bit and change this, because this irregularity (besides being inelegant) is going to be a problem for writing generic code. (I'd like to turn all those special cases into structs. This would have other advantages, like allowing them to have members: imagine having convenient built-in constants like `Int.MIN_VALUE`, `Int.MAX_VALUE`, `Double.INFINITY`...)
So what about enums?
In Java, they're pretty much classes, and their values are objects. However, you're proposing something more similar to C/C++/C#-like enums. Such enums are basically aliases for a subset of values of a different type such as `Int`. In that case, if `Int` is a struct, and an values are all `Ints`, could enums be considered structs as well? Or would they be a new "kind"?

- **Can the underlying type be chosen? What types are allowed?**
You only mentioned `Int`, but it could be useful to be able to choose the underlying type. Other languages allow this to varying degrees: C does not let you choose. C++ and C# lets you to choose, but only integral types (I am not sure why). D allows pretty much any type.
So what should we allow in BlitzMax? Only `Int`, any integral type, any compile-time constant, or even more?

- **What conversions are supported and how are invalid values treated?**
I agree with @GWRon, enums shouldn't have implicit casts to or from `Int` (or whatever underlying type they might have). That would make them type-unsafe and pretty useless, since they'd be essentially the same as regular `Const`s then.
Explicit casts make sense. But if an `Int` can be cast to an enum type, then how are "invalid" values (that do not match any of the enum values) treated? Will they be accepted or will this produce an error at runtime? Will there be a way to check the validity of a value before trying to assign it?

- **What other features will they have?**
For example...
Will enum values have a special `ToString` method or cast to `String` to retrieve the names of their values, as in `Local n:String = EWeekday.Monday.ToString()   ' "Monday"`?
If so, will the reverse be possible?
Will it be possible to iterate over the member values of an enum, as in `For Local d:EWeekday = EachIn EWeekday`?
Will there be support for using them as [flags enums](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/enumeration-types#enumeration-types-as-bit-flags)? (this is related to the previous question about conversions and invalid values)

**Comment by 0nXYZ** [comment]
Yes, please. I think this change would be beneficial, for me at least.

**Comment by HurryStarfish** [comment]
It is already possible to declare a "closed", enum-like type like this:
```
Type EDirection Final
	Global Left:EDirection  = New EDirection
	Global Right:EDirection = New EDirection

	Private
	Method New() End Method
End Type
```
Since the type is final and the constructor is private, new instances can't be created from outside. Only the predefined globals can be used. (If `ReadOnly` could be used on globals, we could also prevent reassigning them, but that is probably not a good idea before #252 is solved).
This pattern essentially gives us an enum-like type with a predefined set of values, which could be used to create something like an EDirection, EWeekday, etc...
<br>
So, to help answer the questions from my previous post, maybe we should make a list:
**What other things do we want from an Enum type, that we can't easily achieve with this pattern?** 

Personally, I'd like to have these:

- Flag enum support: a way to define an Enum so that its values can be combined like bit flags: `RegisterKeyCombination(Commands.SelectAll, EKey.Ctrl | EKey.A)`
- meaningful ToString support: `EWeekday.Monday.ToString()`, if possible, should return "Monday"
- `ForEach` support over the enum values, or even better, a `.Values()` function that returns them as an array
- C interop: conflating a bunch of C constants into an Enum might be useful at times. Those tend to be `#define`s, which cannot be `Extern`-ed, but we might still want to be able to define an Enum with matching values.
For example, some C library to open files might contain:
  ```
  #define FILE_MODE_READ 1
  #define FILE_MODE_WRITE 2
  #define FILE_MODE_READWRITE 3
  void OpenFile(int file_mode);
  ```
  It would be nice to be able to import it like this:
  ```
  Enum EFileMode
  	Read = 1 ' <- explicitly defined values to guarantee they match the C ones
  	Write = 2
  	ReadWrite = 3
  End Enum
  Extern "C"
  	Function OpenFile(fileMode:EFileMode) ' <- compatibility between EFileMode <-> int
  End Extern
  ```
In addition, the following things should be kept in mind:

- integration with reflection: reflection should be able to do inspect enum types, retrieve their values, convert an enum value to its underlying value ("EWeekday.Monday" -> 1) and vice versa ("EWeekday" and 1 -> "Monday")
- ideally "seamless" integration with generics later on
<br>
Does anyone else have additions or a different list?

**Comment by woollybah** [comment]
Yes, that all seems fine.
I'm currently leaning towards something like this for syntax:
```blitzmax
Enum Name:IntegralType [FlagsProperty]
    First,
    Second,
End Enum
```
Where the type would default to Int, but optionally any integral type - I'm not sure about supporting other types (like decimals or object types) unless there's a good reason to do so.

Enums would normally not be supporting "flags" - since it's a slightly different concept - where the particular value may be several combined flags.
To make a particular Enum support flags, we'll use some new keyword (maybe `Flags`, or something more outrageous that I'm unlikely to have already used in half my modules :-p ) to tack onto the end of the declaration of the Enum, like we do with Types.
A ToString() of a flags value would present a comma-separated list of its parts : "First, Second"

Internally, there'll be a load of stuff generated and registered - in much the same way as we already do for types, interfaces and structs. None of it needs to be GC'd, since all the data (names, values, etc) are static. Only a flags ToString() I could see needing to be dynamically generated at runtime - the results of which we may also be able to cache.

**Comment by GWRon** [comment]
Can't we simply said ... use the meta tags ? Just that in that case the compiler already checks enum definitions for meta tags?
```BlitzMax
Enum Name:IntegralType {flags}
    First, 'automatic value: 0
    Second, 'automatic value: 1
    Third, 'automatic value: 2
    Fourth, 'automatic value: 4
    Fifth, 'automatic value: 8
End Enum
```
Another a option would be a new type ... handling the whole bitmask stuff already (`(First + Second).Contains(First) = True`). Might make things way too complex - but seems to be the route @HurryStarfish  likes to go for Strings too.

Regarding "FlagsProperty" - if the "FlagsProperty" keyword would not be used elsewhere, we could also name it `FlagsEnum` - and if we do that, we could introduce a new "structure name" next to `Enum` ... `FlagsEnum` and so get rid of the appended "sub definition".

**Comment by woollybah** [comment]
Flag Enums should probably start at 1, unless a standard zero flag value is included (c# uses `None` for that).

Although we may not want to try auto-populating these values (i.e. raise an error instead), as it's generally a case of bit-shifting by index, and if the user adds their own specific values, we can't really assume what the next value might be.

**Comment by GWRon** [comment]
"None" is what I left out intentionally - think it is up to the developer to define if the first entry is "none" or if "none" is not available at all. Assume an object which has to move in one of four directions. "None" would not enforce a specific "default" direction. 

But the longer I think about it, I see no real need to do so - in such "special cases" one could add another indicator for "move or not moving".

**Comment by HurryStarfish** [comment]
> To make a particular Enum support flags, we'll use some new keyword (maybe `Flags`, or something more outrageous that I'm unlikely to have already used in half my modules :-p )

 Yeah, none of the existing keywords quite fit and "flags" is a common variable name. "BitFlags" might be better, but could still be a variable name. "FlagEnum" might work, but feels a bit redundant when we already write "Enum" on the same line...

Imo we don't need commas between the values in an Enum definition, at least when they're separated by newlines. The values are kinda like `Global` declarations (without the `Global` and the type) and being able to omit the separator feels more BlitzMax-like.

> A ToString() of a flags value would present a comma-separated list of its parts : "First, Second"

Sounds good, although personally I'd prefer "First | Second", since it would mirror the code (and clarify that the value is a union rather than an array or list).

> Where the type would default to Int, but optionally any integral type - I'm not sure about supporting other types (like decimals or object types) unless there's a good reason to do so.

In that case, we could require all the values to be compile time constants. Then, in the case of a flag enum with explicitly defined values, the compiler can ensure that those values are powers of two (unless we actually want to allow "combined" values?).
Also, for non-flag enums, when casting an integer to enum values, imo there should be a runtime check to ensure that the number actually corresponds to one of the enum values. Assigning arbitrary, undefined values should be considered an error. Like array-index-out-of-bounds and null checks, this can be limited to debug builds.

**Comment by HurryStarfish** [comment]
> I'm not sure about supporting other types (like decimals or object types) unless there's a good reason to do so.

After giving it some more thought, I definitely agree with not allowing object types. As long as enum values can only be value types, the enum types themselves can be considered value types.
So we'll have two kinds of value types (structs and enums) just like we already have two kinds of reference types (classes and interfaces). And just like every actual instance of an interface type is also an object of a class, every actual value of an enum type is also an instance of a struct (even though the relationship between the types is a different one).

`Can't we simply said ... use the meta tags ?`
I do not agree with that. Metadata can contain arbitrary strings (so typos won't be caught), and was made to be evaluated at runtime via reflection. I don't like the idea of starting to repurpose it to act as instructions for the compiler; that's what keywords and syntax are for.

**Comment by HurryStarfish** [comment]
As for a None value: since we'll need a value for uninitialized variables (and conversion from Null), we'll need to either force every enum to include a 0 value, or have an explicitly specified default value.

**Comment by woollybah** [comment]
There's a WIP in bcc and brl "enum"  branches.
I'll be working on flags and things next.
And some kind of reflection integration too, I expect... maybe.

**Comment by HurryStarfish** [comment]
> And some kind of reflection integration too, I expect... maybe.

Maybe don't do that yet; I'm about to commit some changes to the reflection code soon (bmx-ng/brl.mod/issues/45). I could look into reflection support for enums too after that.

**Comment by GWRon** [comment]
@HurryStarfish 
Github introduced pull request drafts/sketches. Maybe you want to discuss your reflection changes/proposals that way?
Just want to avoid issues after updating (eg. MaxLua uses the reflection code intensively).

**Comment by woollybah** [comment]
Committed the flags stuff, which seems okay.
It allows you to have things like masks :
```blitzmax
Enum EInc Flags
	None
	One
	Two
	Three
	Four
	Five
	Six
	Seven
	Mask = One | Two | Three | Four | Five | Six | Seven
End Enum
```
A dump of strings and ordinals for this would give
```
None = 0
One = 1
Two = 2
Three = 4
Four = 8
Five = 16
Six = 32
Seven = 64
One|Two|Three|Four|Five|Six|Seven|Mask = 127
```
You can start Flags enum with any value. The default is 0. If you don't provide an initial value, it will either increment from the previous (if it is not a power of 2) or shift left from the previous. If you don't want a zero entry, set your first to 1.

I haven't added a HasFlag(flag) method - Currently there are two methods ToString(), Ordinal() and the function Values(). You can use the binary math operators to do stuff with the Flags enum.

Oh, yes. You can see I'm using "Flags" there. It's parsing for that, but it's not been defined as a keyword yet. BitFlags is okay, I suppose, but I haven't committed to anything yet :-)

Missing some "bounds" checking/rules.
Debugscope is implemented for reflection/debug support. (I haven't considered debug until this very moment. hmm :-p)
Still need to do some tests across imports - eg. iparser probably needs some work. I'll do this next.

**Comment by GWRon** [comment]
Question:
```BlitzMax
Enum EInc Flags
	None
	One
	Two
	Three
	Four
	Five
	Six
	Seven
	Mask = One | Two | Three | Four | Five | Six | Seven
	Test 'which value would this receive?
End Enum
```

**Comment by woollybah** [comment]
> If you don't provide an initial value, it will either increment from the previous (if it is not a power of 2) or shift left from the previous
So, if `Mask` is a power of 2, `Test` will be the next power of 2. Otherwise it will just increment. So I'd imagine `Test` would be `1946`.

**Comment by GWRon** [comment]
But isn't this "incorrect" (somehow).
I understand the logic behind - but it results in values changing" as soon as you adjust your `Mask` value.
Ok, one might assume: "Mask is 1945, so Test becomes Mask+1". Now you decide to add something to the Mask resulting in a "power of two" value. so test becomes no longer "Mask+1" but "Mask*2".

Logicwise the new value is true - but it is not "obvious" for the developer in that moment (except he calculates the resulting numbers in his head and knows the actual number corresponding to "Mask").

**Comment by woollybah** [comment]
Typically, someone creating an `Enum` using `Flags` would know what they intended the values to be.
The rules for auto-populating will be clearly defined in the documentation.

As much as you like to create overly-complicated edge cases, I doubt in general this would be an issue for the majority. Use of auto-populating enums is completely optional. The developer is free to define all the values themselves - which is currently the case when using Consts.

**Comment by GWRon** [comment]
> As much as you like to create overly-complicated edge cases

The edge cases are what create most of the issues here - stuff normally not done or used in special combinations.

**Comment by woollybah** [comment]
Cross-file support for enums is done now, which means you should be able to import a file with an enum and use it locally.

I believe that's the core work completed.
Now I'm off to bah.mod to remove references to "enum"...

**Comment by HurryStarfish** [comment]
```
Mask = One | Two | Three | Four | Five | Six | Seven '1945
Test 'which value would this receive?
```
> So, if `Mask` is a power of 2, `Test` will be the next power of 2. Otherwise it will just increment. So I'd imagine `Test` would be `1946`.

That seems like an error waiting to happen. Imo `Test` should be the next available power of two, no matter what is assigned to `Mask`.
If someone defines a flag enum without explicit numbers, they most likely want the values to be independent flags.
For instance, if I have an enum like this:
```
Enum EDirection Flags
	Up   ' 1
	Down   ' 2
	Left   ' 4
	Right   ' 8
End Enum
```
and later change it to
```
Enum EDirection Flags
	Up   ' 1
	Down   ' 2
	Left   ' 4
	UpLeft = Up | Left   ' 5
	Right   ' 6 ???
End Enum
```
then I most likely did **not** intend for `Right` to suddenly become equivalent to `Down | Left` (2 + 4). Rather, I'd expect any existing code using `Right` to still behave the same way as it did before, so it should still get the next free power of two, which is 8.

**Comment by HurryStarfish** [comment]
On a related note, I just realized my code above would have another bug in it:
I'd also expect the first value in a flag enum to be 1 unless explicitly defined otherwise. If a "none" value is desired, it can be explicitly defined with "= 0", or you could just use `Null` instead.

**Comment by GWRon** [comment]
Think defaulting to "1" for the first is a good idea. And if you really need to start with 0 just define the first item accordingly.

on the other hand: arrays in BlitzMax are zero-based - so doing the opposite (default to 0) might be more "consistent".

**Comment by HurryStarfish** [comment]
What I wrote above was about flag enums in particular. For "regular" enums, starting with 0 does make sense, since variables of that type should only hold values that were actually listed in the enum.
```
Enum EWeekday   ' "regular" enum: only the listed values are valid
	Monday Tuesday Wednesday Thursday Friday Saturday Sunday
End Enum

Enum EDirection Flags   ' flags enum: "none of them" is a valid value too
	Left Right Up Down
End Enum
```
So an uninitialized variable `Local day:EWeekday` and `Local joystickInput:EDirection` can both contain 0 by default. For `day`, this means `Monday`, for `joystickInput:EDirection` it means "no direction".

**Comment by HurryStarfish** [comment]
I've gave the current build a try :)

A few things I've found so far:
```
SuperStrict
Framework BRL.StandardIO

Enum EDir Flags
	Left Right Up Down
End Enum

Local s:String = EDir.Left ' should not allow implicit conversions to numbers or strings;
                           ' should require explicit cast to Int or .Ordinal() or .ToString()

' is there already a way to convert an Int back to an EDir value?

Local noDir:EDir
Print noDir.Ordinal() ' should print 0

Print EDir(Null).Ordinal() ' causes error, should print 0

Local ul:String = (EDir.Up | EDir.Left).Ordinal()­ ' causes error, should print 5

Print((EDir.Up | EDir.Left).Ordinal()) ' causes error, should print 5

Enum ETest:Byte Flags
	A B C D E F G H I J K L ' should cause a compile error because not enough number values are available
End Enum
```

**Comment by woollybah** [comment]
So,
> Local noDir:EDir
Print noDir.ToString()

Would print ?

**Comment by HurryStarfish** [comment]
Hmm, not sure. It would be the string representation for "no flag"; the same as `Print EDir(Null)`, `Print EDir.Left & EDir.Right` or `Print EDir.Left ~EDir.Left`. Judging from the latter two, which already compile, this is currently an empty string. Maybe that's fine? It's a bit counterintuitive if you just want to use `Print` and don't see anything, but it does have the nice property of making the string representation a list of all active flags concatenated with `|`. No flag = no output.

**Comment by woollybah** [comment]
I've just added support for debugging. It shows the String value for the enum, which I think is what you'd expect.

**Comment by woollybah** [comment]
Well, that's it all merged into master.
It still currently uses `Flags` to define a flags enum, but it's not been defined as a keyword yet.

**Comment by woollybah** [comment]
Added some docs : https://blitzmax.org/docs/en/language/enums/

**Comment by DivineDominion** [comment]
I know this issue is closed, but I'd like to drop my 2¢  and say I really like `OptionSet` in Swift for what was discussed as `Enum ... Flags` in here.
