### ISSUE TITLE
Expression has no scope: more details?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#391]
If you try to call a method of a number you receive a "Expression has no scope" error. I think it is not a kind of error the usual BlitzMax user understands.

```BlitzMax
local d:double = 1.0:double

Function passString(s:string)
End Function

passString(d.ToString())
```
This happens as for now the numbers are no objects and do not have an inbuilt "ToString()" and while you could easily do a cast `String(g)` it would be nice to have a "ToString(").

Back to the original topic: the error message itself.
If you compile that with vanilla the error is: `Identifier 'ToString' not found`. I think the error message is better explaining to a normal developer what is faulty in the code.

I think you might even write the whole expression there ... and this would be `Function or Method 'ToString()' not found in 'd'`. "d" would become every piece of code constructing the used "object" for the function/method call. So a
```BlitzMax
passString( (1.0/d).ToString() )
```
would error out with: `Function or method 'ToString()' not found in '(1.0/d).`

That way the error would become pretty elaborative.

BUT ... "identifier 'X' not found." might be still more suitable. A Type might have a field containing a callback function reference. Blaming a missing "function/method" there would be misleading (as you might be referencing a typo'd function reference instead of a defined function).

Another side note: the error message indicator only contains the line number ("[C:/Path/file.bmx;5:0]"). If the caret / position in the line would be filled properly the error would be markable easier (not underlining the whole line but only the corresponding part).

**Comment by HurryStarfish** [comment]
As mentioned in #382, at some point I'd like to make the primitive types behave like structs and also give them members (`.ToString()` included), which would take care of this problem.
But until then, I agree the current message can be a bit confusing.

> `Function or method 'ToString()' not found in '(1.0/d).`

I'd find something like `Member 'ToString' not found in type 'Double'` more useful. I can already see the `(1.0/d)` in the code, repeating that in the error provides no additional information. But telling me the exact type that expression resolved to can help me realize what went wrong (especially in cases where it isn't `Double` but a class/interface, and the error is due to some inheritance-related mistake).

**Comment by GWRon** [comment]
I agree with your proposed message. "Member" or "Identifier" suits better.

Regarding the "type name" - yes, this also is a better idea than mine - as long as the error line indicator contains a proper caret position.
