### ISSUE TITLE
Confusing error message for missing method body

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bcc#392]
When "upgrading" an interface to a class, this mistake can happen:
```
SuperStrict
Framework BRL.StandardIO

Type T
	Method M()
End Type
```
The error message for this is somewhat confusing:

> Compile Error: Syntax error - expecting identifier, but found '
> '

**Comment by GWRon** [comment]
Same error message for this:
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Local arr:String[] = new String[10]
'attention to the dot at the end: " elements". instead of " elements."
print "Array contains " + arr + " elements".
```
- it expects a method/function because of the "spelling mistake" of the dot being outside of the string
- it does not error out of the missing `.length` or `Unable to convert from String Array to String.` -> seems it does check this portion of the code later than the missing "method/function call" of the string. So no "left to right evaluation" and I hope this cannot raise other issues (doubt that)
