### ISSUE TITLE
Select inbuiltFunctionWithOutBracket differs to vanilla

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#418]
There is a behaviour difference between VANILLA and NG:

```BlitzMax
SuperStrict
Framework Brl.StandardIO


Local s:String = "A"

Function Test:Int()
	Return 1
End Function


'Rem
'this one is catched in VANILLA and NG
Select Test 'no brackets!
	Case 1    Print "1" 'Compile Error: Unable to convert from Int to Int().
	Default   Print "other"
End Select
'End Rem


Rem
'now try with an "inbuilt" function
Select s.ToLower 'no brackets!
	'NG: prints this
	'VANILLA: Compile Error: Unable To convert from 'String' to 'String()'
	Case "a"  Print "a" 
	Default   Print "other"
End Select
End Rem


Rem
'now I want to compare functions ;-)
Local _func:Int() = Test

Select Test
	Case _func  Print "_func"     'VANILLA prints this
	Default     Print "different" 'NG prints this
End Select
End Rem
```

Only case 1 works the same on both.

**Comment by HurryStarfish** [comment]
Interesting...
I can't test it right now, but the "inbuilt" case looks like NG calls the method, although it shouldn't (since `()`-less calls are only valid as statements). Does this also happens with methods of user-defined types?
I don't have a good guess what happens in the "comparison" case though. Maybe it calls the first function and compares the returned `Int` with the pointer of the other function or something like that...

**Comment by GWRon** [comment]
Just to avoid ambiguity I added a varying return value of the function. Else someone might have thought of a "test() = _func()" test instead of comparing memory addresses.

```BlitzMax
SuperStrict
Framework Brl.StandardIO


Local s:String = "A"
Global l:Int
Function Test:Int()
	l :+ 1
	Return l
End Function


Rem
'this one is catched:
Select Test 'no brackets!
	Case 1    Print "1" 'Compile Error: Unable to convert from Int to Int().
	Default   Print "other"
End Select
End Rem


Rem
'now try with an "inbuilt" function
Select s.ToLower 'no brackets!
	'NG: prints this
	'VANILLA: Compile Error: Unable To convert from 'String' to 'String()'
	Case "a"  Print "a" 
	Default   Print "other"
End Select
End Rem


'Rem
'now I want to compare functions ;-)
Local _func:Int() = Test

Select Test
	Case _func  Print "_func"     'VANILLA prints this
	Default     Print "different" 'NG prints this
End Select
'End Rem
```

**Comment by HurryStarfish** [comment]
You've found two different, unrelated problems here.

The first one is the fact that calls to methods and functions can be made without parentheses even when they're not statements. I've reported it separately as #444.

The second one is the fact that directly referencing a function in the head of a `Select` statement results in incorrect C code generation. More precisely, this happens:
1. ```BlitzMax
   Select 1
   	Case 2
   End Select
   ```
   ```C
   BBINT bbt_=1;
   if(bbt_==2){
   }
   ```
   Basic example of how `Select` gets translated.
2. ```BlitzMax
   Select _func
   	Case Test
   End Select
   ```
   ```C
   BBINT(* bbt_)()=bbt__func;
   if(bbt_==_m_untitled2_Test){
   }
   ```
   Looks as expected, same pattern as above.
3. ```BlitzMax
   Select Test
   	Case _func
   End Select
   ```
   ```C
   BBINT(* bbt_)() = bbt_;
   if(bbt_==bbt__func){
   }
   ```
   Incorrect initialization of `bbt_` with itself instead of `_m_untitled2_Test`.
4. ```BlitzMax
   Select Test
   	Case Test
   End Select
   ```
   ```C
   BBINT(* bbt_)() = bbt_;
   if(bbt_==bbt_){
   }
   ```
   Not only is the initialization incorrect like in 3., but also the `Case Test`, despite being correctly generated in 2..

**Comment by GWRon** [comment]
May becomes month of the "interesting bugs". Keeps @woollybah 's awareness level up :)

**Comment by GWRon** [comment]
```BlitzMax
'now try with an "inbuilt" function
Select s.ToLower 'no brackets!
	'NG: prints this
	'VANILLA: Compile Error: Unable To convert from 'String' to 'String()'
	Case "a"  Print "a" 
	Default   Print "other"
End Select
```
Now now no longer prints "a" ... but `Compile Error: Method cannot be used as a function pointer`. So it catches it, but does not print the same error message as vanilla.
This is OK for me.
