### ISSUE TITLE
New Object - what does it do?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#425]
If I use this:
```BlitzMax
SuperStrict
Framework Brl.StandardIO

local o:object = new Object
```
what does `o` then contain? In Vanilla it does not compile (with a misleading error message of course ;-)) but NG just allows it.

**Comment by HurryStarfish** [comment]
I'm not sure I understand the question... it should do exactly what you'd expect: create a new `Object` instance and assign it to `o`.

**Comment by GWRon** [comment]
Isn't an object ... kind of "abstract". I mean, it is some kind of base class for all types. So what could I do with a "new object".
And if it was useful - why can't you create one in vanilla?

**Comment by HurryStarfish** [comment]
Well, the reason you can't do this in vanilla is not technically because it's abstract, but because `New Object` counts as a syntax error there.
I don't think it's useful. At least I can't really think of any use for it (some situation where you might want a "neutral" dummy object?). But I can't think of a reason to disallow it either. `Object` is a class, and it has no abstract members, so there's no harm in being able to create instances of it.

**Comment by GWRon** [comment]
Thanks - the "neutral object" thing was the only usage idea I had too ;-)
