### ISSUE TITLE
Compile error: Auto array has no type (objArr :+ [null])

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#442]
When trying to add an empty array to a object array I receive the error `Auto array has no type` - which explains what it doesn't expect ;-)

```BlitzMax
Local myarr:TMyType[] '= ...

'add an empty position
myarr :+ [null] '<-- error

'add an empty position
myarr :+ new TMyType[1] '<-- works

'add  an empty position
myarr = myarr[ .. myarr.length+1] '<-- works too
```
Isn't "null" valid for all objects? So it should "suit" to all object arrays?

**Comment by HurryStarfish** [comment]
> Isn't "null" valid for all objects? So it should "suit" to all object arrays?

Indeed, but and operators like `:+` aren't target typed, and `Null[]` isn't a valid type, so `[Null]` is not a valid array literal.

When you write `myarr :+ [Null]`, youre telling the compiler to
1. create a `[Null]` array and then
2. add that array to `myarr`.

Step 1 is not allowed, because the compiler doesn't know what the type of that array literal is supposed to be. Knowing that it should be `TMyType[]` would require "looking ahead" to the left, which it doesn't do because it's normally unnecessary.
`New TMyType[1]` works, because in that case you're telling the compiler the array type. `[TMyType(Null)]` would work too.

**Comment by GWRon** [comment]
Thanks for the elaborative reply.

BCC is capable of looking ahead (and it does this when parsing the lines). This means BCC is knowing what stands on the left hand side - and what on the right hand side of the whole expression. The problem is that it disregards the lhs when evaluating the rhs. It got "array containing null" and needs to understand that this can be assigned.

Also I do not understand why it handles `[Null]` as a array of "type Null" - shouldn't it fall back to some kind of "undefined" or so?

Why am I asking for this "feature"? Consistency.
```
local x:int = 0
local arr:int[] = [1,2,3]

x :+ 1 'ok
arr :+ arr 'ok -append array to itself (for whatever reason)
x :+ Null 'ok - I can add Null
arr :+ [Null] 'adding a null-typed-array fails
```
I understand the current limitation (with Null[] being no valid type) yet it should be possible to do so.
Also I am not aware of potential breaks in "language consistency" if such a thing was added - is the usage of "Null" limited somewhere else too?

**Comment by HurryStarfish** [comment]
> Why am I asking for this "feature"? Consistency.
> arr :+ [Null] 'adding a null-typed-array fails

Keep in mind that it's not the addition that fails, it's the creation of `[Null]`. There's nothing inconsistent about the addition.

> Also I do not understand why it handles [Null] as a array of "type Null" - shouldn't it fall back to some kind of "undefined" or so?

> is the usage of "Null" limited somewhere else too?

`Null` has its own special type, because can turn into many different things when converted to another type. The null type can be converted into any other type (via cast or assignment), but you can't really do anything else with it. For example, while you can do `Local i:Int = Null`, you can't do anything like `Local i:Int = Null + Null`, which would require converting the `Null`s to `Int` *before* doing the addition. And similarly, you can't do `Local a:Int[] = [Null]`.
Of course, since you can't *write* the null type, you also can't declare a variable of it, or a function that returns it, etc.

> I understand the current limitation (with Null[] being no valid type) yet it should be possible to do so.

Not sure how much effort it would be to implement such target typing for array literals. You can already do things that *look* like it in NG (`Local a:Double[] = [1, 2, 3]` works, unlike in vanilla), but that is a conversion at runtime rather than target typing - it also works with variables. While personally I don't see much of a point in implementing this just for `[Null]`, it might also improve the performance of things like the afromentioned `Local a:Double[] = [1, 2, 3]`.

**Comment by woollybah** [comment]
I also have no inclination to implement this either.
You can always cast your null to the correct type :-)

**Comment by GWRon** [comment]
@HurryStarfish 
So you say "target typing for array literals" would improve performance? 
Am not sure if I understood you correctly.


@woollybah 
There are more important things to do for now :-)

**Comment by HurryStarfish** [comment]
> So you say "target typing for array literals" would improve performance?
> Am not sure if I understood you correctly.

Upon taking a closer look: nevermind, I was mistaken.
I assumed that when you write something like `Local a:Double[]; a = a + [1]`, NG converts the `Int` array into a `Double` array at runtime before doing the addition. It does not; turns out I found a bug instead. :)
Reported as #443.

**Comment by GWRon** [comment]
Glad that my "stupid" ideas shoos the bugs out of their holes :)
