### ISSUE TITLE
Enhance -ud option to allow for specific values

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bcc#464]
Currently, the `-ud` options takes a basic comma-separated list of conditionals - by default these represent `True` or `On`. The lack of a particular conditional assumes `False` or `Off`.

It would be useful if we could also optionally specify a value with the conditional, so : `-ud windows_version=500`

The provided value would be set against the conditional, instead of the default which is currently `True` or `1`.

`bcc` may already support more complex conditional evaluation (e.g. ?windows > 100) but I haven't tested it. Otherwise, we may consider adding it in the future.

**Comment by GWRon** [comment]
> `bcc` may already support more complex conditional evaluation (e.g. ?windows > 100) but I haven't tested it.

Sorry for having brought up fuzz with my issue - for now it is not possible to have `?WINDOWS_VERSION > 100` but I think it could be "straight forward" to add support for proper expression handling in BCC (especially as it is only a "compile time" thing, the added workload could be neglectable).


@ -ud
How does BMK handle custom conditionals when it comes to caching?
Assume I use two audio backends (PulseAudio is not available/installed on all Linux distributions).
I could now have two BMK runs to compile two different compilation runs. Each one gets another `user_defs` passed (currently this needs to be done via .bmk files rather command line params?):
`bmk ... -o mybinary.rtaudio.bin`
`bmk ... -o mybinary.freeaudio.bin`

Each call resulted in different `-ud` params passed to BCC. Now during the first compilation "rtaudio" was set to true. My audio-source-file is compiled and then no longer changed (would not need a recompilation). Next I run the second compilation with "freeaudio" being true now. M audio-source-file is not changed and therefore wont be recompiled when compiling in "quick mode".

result is that the custom conditional in the second run is ignored. How to tackle that? Somewhere BCC/BMK should be made aware of files using "dynamic" stuff (here "custom conditionals") so that their (non-)existence leads to a recompilation.

**Comment by woollybah** [comment]
For now, if you are messing around with changing these between builds, you'll need to rebuild the affected parts.
