### ISSUE TITLE
Function and Method with same definition not allowed

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#504]
Discord channel user mingw dropped this example showing that it is not possible to have a function and a method with the same name:
```
Type TTest
    Function Test()
        DebugLog "f"
    End Function
    
    Method Test()
        DebugLog "m"
    End Method
End Type

Local t:TTest=New TTest
t.Test()
TTest.Test()
```
BCC blames a duplicate definition.

```
I: "How does an instance know that "t.Test()" is calling the method? It could also call the function"

They: "It's logical - you need to look for a method. call priority: Self.Method->Super.Method->Self.Function->Super.Function->Global.Function. Apparently here it is implemented a little differently ..."
```

So the user asks for a "method >> function" priority handling.

**Comment by HurryStarfish** [comment]
This is basically asking for a form of overloading based on "function vs. method". It would bring a whole bunch of complications, for example:
- What if I wanted to call the function from somewhere inside the type?
- What if the method isn't accessible due to visibility (public/protected/private), but the function is?
- What about other kinds of members? Can I give a field and a method with the same name as well? If yes, which has priority? If no, why not?

It might be possible to come up with a ruleset to resolve this, but it would end up very complicated and confusing. I don't see any benefits do doing this either, so I don't support this idea.
