### ISSUE TITLE
Using "void"-functions as arguments leads to "Illegal expression type"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#70]
```BlitzMax
SuperStrict
Framework Brl.StandardIO

'no return value!
Function a(i:Int)
End Function

Function b:Int()
	Return a(1) - a(2)
End Function

b()
```

Fails with "Illegal expression type" on the _Return a(1) - a(2)__ call. On Vanilla it compiles and would return "0".

**Comment by woollybah** [comment]
I'd say this is a valid error. Perhaps the error message should be more explicit, but I think it should fail, regardless of what legacy bcc does.

**Comment by GWRon** [comment]
If course I think NG is allowed to error on more things - as long as it explains why it is failing. Do not misunderstand me: I know that the issues are errors in my code :p

**Comment by GWRon** [comment]
While "return a(1)" is a valid error - shouldnt a subtraction of "void" result in something like 0?

No ... I am not "joking" (albeit I started this comment to write something not that serious)

The function b:int() returns an integer value. When doing the math operation of "void - void" you should end up with "0", same for "void/void" = "1". I mean, these are rare special cases and really constructed ... but maybe there are more cases of "math(void)" returning real mathematic values.

I still understand, that the above is something really "constructed" and no real-world-scenario.

**Comment by woollybah** [comment]
If you are using Strict, then you can do what you like.
However, I think SuperStrict should at least try to be super-strict, otherwise we may want to rename it to something like "MostlySuperStrict" :-)

In legacy BlitzMax, all functions return at least Int, regardless of strictness. C doesn't let you mix and match, and it turns out that emscripten *really* doesn't like you doing "fun" things with inappropriately mixed function signatures. (You may consider emscripten to be ReallySuperStrict)

**Comment by GWRon** [comment]
Like said: I am totally open for just not allowing void as result for something different ... stay tuned for next issues :p


You may close this issue when introducing an error-message ("invalid return type").
