### ISSUE TITLE
Module interfaces are in the wrong place

### ISSUE THREAD

**Issue by Sashkakuhta** [bmx-ng/bcc#84]
I'm probably found an issue: when initially doing makemods, process fails with message like "Can't find interface for module xxx". I'm tried it on windows 7, 8.1 and XP with same results. I'm found out that for some reasons .I files are placed in the .bmx folder and have wrong name (they have a name of mod source file, but not mod name). Copying and renaming interface file for each mod is a really big amount of work.

**Comment by GWRon** [comment]
Does this happen for all modules or some custom mods?

Can you give he "path" you are using (eg. "C:\BlitzMaxNG\mods\mymod.mod\mymod.mod\mymod.bmx") ?

**Comment by Sashkakuhta** [comment]
This happens for all modules, path is "D:\BlitzMaxNG\mod\..."
path in bcc.conf is "D:\BlitzMaxNG\"

**Comment by Sashkakuhta** [comment]
Well, everything works OK when i delete bcc.conf, but anyway it breaks with bcc.conf even if it configured as it should

**Comment by GWRon** [comment]
I tried it too ... it started compiling and then errored out. changing the path to something incorrect (like your path - because it already contained an "trailing slash") the error changed - but was still an error.

So what does this bcc.conf do ? If this file exists, the "environment variable BMXPATH" is set to the value   we defined in "bcc.conf".

This BMXPATH is used for ...the BlitzMax function `BlitzMaxPath$()` defined in __brl.mod/maxutil.mod/maxutil.bmx __

Ok ... so what differs to the things we wrote in bcc.conf and to the one `BlitzMaxPath()` will return if we do not have the BMXPATH defined? ... the answer was simple: slashes.

I now used `BMXPATH_WIN32=E:/BMX-NG` and it compiled ... 

Seems we should replace the read value to contain "slashes".

**Comment by GWRon** [comment]
I made a simple change to the corresponding source file and send out a pull request. If Brucey thinks the same he will surely merge it - else he has to come up with another solution (I might have not seen all consequences of this change).

**Comment by woollybah** [comment]
I think I will also add a note that you don't need bcc.conf for general use. It's only useful if bcc is not the BlitzMax/bin folder - for example if you are debugging it from another IDE (when you will be inheriting BMXPATH from that IDE).

**Comment by woollybah** [comment]
Code fixed, comment added.
